import { Sound } from "../types";

const SOUND_TITLES: Record<string, Record<string, string>> = {
    "1": { en: "Success chime", ko: "띠리링" },
    "2": { en: "Success trumpet", ko: "성공 트럼펫" },
    "3": { en: "Tada fanfare", ko: "빵빠레" },
    "4": { en: "Applause", ko: "박수" },
    "5": { en: "Failure trombone", ko: "실패 트럼본" },
    "6": { en: "Failure beeps", ko: "실패 삐" },
    "7": { en: "Crowd laugh", ko: "군중 웃음" },
    "8": { en: "Drumroll", ko: "두구두구두구" },
    "9": { en: "Whoosh", ko: "휙" },
    "12": { en: "Punch", ko: "펀치" },
};

export const getDefaultSounds = (lang: string = 'en'): Sound[] => {
    // Fallback to 'en' if lang is not 'ko' (expandable later)
    const targetLang = lang === 'ko' ? 'ko' : 'en';

    return [
        {
            id: "1",
            title: SOUND_TITLES["1"][targetLang],
            fileUrl: `https://${import.meta.env.VITE_SUPABASE_PROJECT_ID}.supabase.co/storage/v1/object/public/defaultAudio/success_chime.wav`,
            duration: 2,
            hotkey: "Digit1",
            color: "bg-green-500",
            volume: 0.5,
            emoji: "✅",
            isDefault: true,
        },
        {
            id: "2",
            title: SOUND_TITLES["2"][targetLang],
            fileUrl: "https://adutuuffuthtwxqprnqg.supabase.co/storage/v1/object/public/defaultAudio/success_trumpet.mp3",
            duration: 3,
            hotkey: "Digit2",
            color: "bg-emerald-500",
            volume: 0.5,
            emoji: "🎺",
            isDefault: true,
        },
        {
            id: "3",
            title: SOUND_TITLES["3"][targetLang],
            fileUrl: "https://adutuuffuthtwxqprnqg.supabase.co/storage/v1/object/public/defaultAudio/tada_fanfare.flac",
            duration: 3,
            hotkey: "Digit3",
            color: "bg-yellow-500",
            volume: 0.5,
            emoji: "🎉",
            isDefault: true,
        },
        {
            id: "4",
            title: SOUND_TITLES["4"][targetLang],
            fileUrl: "https://adutuuffuthtwxqprnqg.supabase.co/storage/v1/object/public/defaultAudio/applause.wav",
            duration: 5,
            hotkey: "Digit4",
            color: "bg-purple-500",
            volume: 0.5,
            emoji: "👏",
            isDefault: true,
        },
        {
            id: "5",
            title: SOUND_TITLES["5"][targetLang],
            fileUrl: "https://adutuuffuthtwxqprnqg.supabase.co/storage/v1/object/public/defaultAudio/failure_trombone.wav",
            duration: 3,
            hotkey: "Digit5",
            color: "bg-red-500",
            volume: 0.5,
            emoji: "📯",
            isDefault: true,
        },
        {
            id: "6",
            title: SOUND_TITLES["6"][targetLang],
            fileUrl: "https://adutuuffuthtwxqprnqg.supabase.co/storage/v1/object/public/defaultAudio/failure_beeps.wav",
            duration: 2,
            hotkey: "KeyQ",
            color: "bg-orange-500",
            volume: 0.5,
            emoji: "🚨",
            isDefault: true,
        },
        {
            id: "7",
            title: SOUND_TITLES["7"][targetLang],
            fileUrl: "https://adutuuffuthtwxqprnqg.supabase.co/storage/v1/object/public/defaultAudio/crowd_laugh.mp3",
            duration: 4,
            hotkey: "KeyW",
            color: "bg-pink-500",
            volume: 0.5,
            emoji: "😂",
            isDefault: true,
        },
        {
            id: "8",
            title: SOUND_TITLES["8"][targetLang],
            fileUrl: "https://adutuuffuthtwxqprnqg.supabase.co/storage/v1/object/public/defaultAudio/drumroll.wav",
            duration: 4,
            hotkey: "KeyE",
            color: "bg-blue-500",
            volume: 0.5,
            emoji: "🥁",
            isDefault: true,
        },
        {
            id: "9",
            title: SOUND_TITLES["9"][targetLang],
            fileUrl: "https://adutuuffuthtwxqprnqg.supabase.co/storage/v1/object/public/defaultAudio/whoosh.flac",
            duration: 1,
            hotkey: "KeyR",
            color: "bg-cyan-500",
            volume: 0.5,
            emoji: "💨",
            isDefault: true,
        },
        {
            id: "12",
            title: SOUND_TITLES["12"][targetLang],
            fileUrl: "https://adutuuffuthtwxqprnqg.supabase.co/storage/v1/object/public/defaultAudio/punch.wav",
            duration: 1,
            hotkey: "KeyT",
            color: "bg-slate-500",
            volume: 0.5,
            emoji: "👊",
            isDefault: true,
        },
    ];
};

export const DEFAULT_SOUNDS = getDefaultSounds('en'); // Backwards compatibility if import directly, but prefer func
